title: Freeopcua.github.io
description: "FreeOpcUa: Open Source Rust and Python OPC-UA Client and Server Libraries and Tools"
google_analytics:
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
